export const ChartData =[
    {
        id:1,
        month:"January",
        Sale:500,
        Return:50
    },
    {
        id:2,
        month:"February",
        Sale:1500,
        Return:105
    },
    {
        id:3,
        month:"March",
        Sale:600,
        Return:128
    },
    {
        id:4,
        month:"April",
        Sale:900,
        Return:52
    },
    {
        id:5,
        month:"May",
        Sale:900,
        Return:500
    },
    {
        id:6,
        month:"June",
        Sale:100,
        Return:0
    },
    {
        id:7,
        month:"July",
        Sale:800,
        Return:190
    },
]